# https://www.playframework.com/documentation/latest/Configuration

play.filters.enabled    += play.filters.cors.CORSFilter
play.filters.enabled    += play.filters.hosts.AllowedHostsFilter
play.filters.disabled   += play.filters.csrf.CSRFFilter
play.filters.headers.frameOptions = null
play.http.parser.maxMemoryBuffer  = 50MB
play.http.secret.key=";c:f@qu^z80<:XRo/;ZNhpPcIo_hG9o0Q^sHG;GYAiJAB6_?iq4pF?>OhVjq</eO"

play.filters.hosts {
  allowed = ["."]
}

db.default.driver   = org.postgresql.Driver
db.default.url      = "jdbc:postgresql://localhost:5432/farm"
db.default.username = "nuge"
db.default.password = "badaiveranda"

app {
base_url = "localhost:9000"
}